export const FETCH_OFFERINGS_REQUEST = 'FETCH_OFFERINGS_REQUEST' 
export const FETCH_OFFERINGS_SUCCESS = 'FETCH_OFFERINGS_SUCCESS'
export const LOAD_MORE_OFFERINGS_SUCCESS = 'LOAD_MORE_OFFERINGS_SUCCESS'
export const FETCH_OFFERINGS_FAILURE = 'FETCH_OFFERINGS_FAILURE'